setup.kibana:
  host: ${KIBANA_HOST}
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
  protocol: https

output.elasticsearch:
  hosts: ["${ES_HOST}"]
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  protocol: https


# metricbeat.config.modules:
#   # Glob pattern for configuration loading
#   path: ${path.config}/modules.d/*.yml
#   # Set to true to enable config reloading
#   reload.enabled: false    

ssl:
  enabled: true
  certificate_authorities: ['/usr/share/metricbeat/config/ca.crt']
  certificate: '/usr/share/metricbeat/config/node.crt'
  key: '/usr/share/metricbeat/config/node.key'
  client_authentication: none


monitoring.enabled: true
monitoring.elasticsearch:
  username: ${ES_MONITORING_USERNAME}
  password: ${ES_MONITORING_PASSWORD}

setup.ilm:
  enabled: auto
  index: metricbeat
  rollover_alias: metricbeat
  pattern: "{now/d}-000001"
  check_exists: false


metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["${PROMETHEUS_HOSTS}"]
    enabled: true
    username: ${PROMETHEUS_USER}
    password: ${PROMETHEUS_PASSWORD}
    metrics_path: /metrics
