setup.kibana:
  host: ${KIBANA_HOST}
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
  protocol: https

output.elasticsearch:
  hosts: ["${ES_HOST}"]
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  index: metricbeat
  protocol: https
  ssl.verification_mode: "none"

ssl:
  enabled: false

setup.ilm.enabled: false
setup.template.name: metricbeat
setup.template.pattern: metricbeat-*
setup.template.overwrite: false

monitoring.enabled: false
monitoring.elasticsearch:
  username: ${ES_MONITORING_USERNAME}
  password: ${ES_MONITORING_PASSWORD}

metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["${METRIC_1_EXPORTER_HOST}"]
    enabled: true
    username: ${METRIC_1_USER}
    password: ${METRIC_1_PASSWORD}
    metrics_path: /metrics
    ssl.verification_mode: "none"

  - module: prometheus
    period: 300s
    hosts: ["${METRIC_REDIS_EXPORTER_HOST}"]
    enabled: true
    username: ${METRIC_REDIS_USER}
    password: ${METRIC_REDIS_PASSWORD}
    metrics_path: /metrics
    ssl.verification_mode: "none"

  - module: prometheus
    period: 10s
    hosts: ["${DATAFLOW_DEV_EXPORTER_HOST}"]
    enabled: true
    metrics_path: /admin/metrics/
    ssl.verification_mode: "none"
