setup.kibana:
  host: ${KIBANA_HOST}
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
  protocol: https

output.elasticsearch:
  hosts: ["${ES_HOST}"]
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  index: "metricbeat"
  protocol: https
  ssl.verification_mode: "none"
  
ssl:
  enabled: false

setup.template.name: "metricbeat"
monitoring.enabled: true
monitoring.elasticsearch:
  username: ${ES_MONITORING_USERNAME}
  password: ${ES_MONITORING_PASSWORD}

metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["${METRIC_1_EXPORTER_HOST}"]
    enabled: true
    username: ${METRIC_1_USER}
    password: ${METRIC_1_PASSWORD}
    metrics_path: /metrics
    ssl.verification_mode: "none"
