setup.kibana:
  host: ${KIBANA_HOST}
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
  protocol: https

output.elasticsearch:
  hosts: ["${ES_HOST}"]
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  index: metricbeat
  protocol: https
  ssl.verification_mode: "none"
  
ssl:
  enabled: false

setup.ilm.enabled: false
setup.template.name: metricbeat
setup.template.pattern: metricbeat-*
setup.template.overwrite: false

monitoring.enabled: false
monitoring.elasticsearch:
  username: ${ES_MONITORING_USERNAME}
  password: ${ES_MONITORING_PASSWORD}

