setup.kibana:
  host: ${KIBANA_HOST}
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
  protocol: https

output.elasticsearch:
  hosts: ["${ES_HOST}"]
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  protocol: https
  verification_mode: "none"
  
ssl:
  enabled: false
  certificate_authorities: ['/usr/share/metricbeat/config/ca.crt']
  certificate: '/usr/share/metricbeat/config/node.crt'
  key: '/usr/share/metricbeat/config/node.key'
  client_authentication: none
  verification_mode: "none"

monitoring.enabled: true
monitoring.elasticsearch:
  username: ${ES_MONITORING_USERNAME}
  password: ${ES_MONITORING_PASSWORD}

setup.ilm:
  enabled: auto
  index: metricbeat
  rollover_alias: metricbeat
  pattern: "{now/d}-000001"
  check_exists: false


metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["${METRIC_1_EXPORTER_HOST}"]
    enabled: true
    username: ${METRIC_1_USER}
    password: ${METRIC_1_PASSWORD}
    metrics_path: /metrics
    ssl.verification_mode: "none"
