################### APM Server Configuration #########################
logging.level: "${APM_LOG_LEVEL}"

############################# APM Server ######################################


apm-server:
  # Defines the host and port the server is listening on.  use "unix:/path/to.sock" to listen on a unix domain socket.
  host: "0.0.0.0:8200"

  # Authorization token to be checked. If a token is set here the agents must
  # send their token in the following format: Authorization: Bearer <secret-token>.
  # It is recommended to use an authorization token in combination with SSL enabled,
  # and save the token in the beats keystore.
  secret_token: "${APM_SECRET_TOKEN}"

  expvar:
    enabled: true
    # Url to expose expvar
    url: "/debug/vars"

  # Enable secure communication between APM agents and the server. By default ssl is disabled.
  ssl:
    enabled: true
    certificate_authorities: ['/usr/share/apm-server/config/ca.crt']
    certificate: '/usr/share/apm-server/config/node.crt'
    key: '/usr/share/apm-server/config/node.key'
    client_authentication: none

#=====================  Index Template Setup ==================================

setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 5

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["${ES_HOST}"]
  # Optional protocol and basic auth credentials.
  protocol: "https"
  username: "${ES_USERNAME}"
  password: "${ES_PASSWORD}"
  ssl.verification_mode: none
  # Number of workers per es host
  worker: 8 
  bulk_max_size: 5120

  indices:
    - index: "apm-%{[observer.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"

    - index: "apm-%{[observer.version]}-error-%{+xxxx.ww}"
      when.contains:
        processor.event: "error"

    - index: "apm-%{[observer.version]}-transaction-%{+xxxx.ww}"
      when.contains:
        processor.event: "transaction"

    - index: "apm-%{[observer.version]}-span-%{+xxxx.ww}"
      when.contains:
        processor.event: "span"

    - index: "apm-%{[observer.version]}-metric-%{+xxxx.ww}"
      when.contains:
        processor.event: "metric"

    - index: "apm-%{[observer.version]}-onboarding-%{+xxxx.ww}"
      when.contains:
        processor.event: "onboarding"


#============================== Internal Queue =================================
queue:
  mem:
    # Max number of events the queue can buffer
    events: 120000


#==============================  Kibana Config =================================

kibana:
  enabled: true
  host: "${KIBANA_URL}"
  protocol: https

#============================== Xpack Monitoring ===============================
monitoring.enabled: true
monitoring.elasticsearch:
  username: "${ES_MONITORING_USERNAME}"
  password: "${ES_MONITORING_PASSWORD}"
