output.elasticsearch:
  hosts: ["${ES_HOST}"]
  protocol: "https"
  username: "${ES_USERNAME}"
  password: "${ES_PASSWORD}"
  ssl.verification_mode: none

setup.ilm.enabled: auto
setup.ilm.rollover_alias: "dit-o365"
setup.ilm.pattern: "{now/d}-000001"

filebeat.modules:
  - module: o365
    audit:
      enabled: true
      var.application_id: "${APPLICATION_ID}"
      var.tenants:
        - id: "${TENANT_ID}"
          name: "${TENANT_HOSTNAME}"
      var.client_secret: "${CLIENT_SECRET}"

monitoring:
  enabled: true
  elasticsearch:
    username: "${ES_MONITORING_USERNAME}"
    password: "${ES_MONITORING_PASSWORD}"
